version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8-openj9
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      "VERSION": "1.12.2"
      "FORGE_VERSION": "14.23.5.2847"
      "ONLINE_MODE": "FALSE"
      "MEMORY": "6G"
      "MODPACK": "https://raw.githubusercontent.com/sethmachine/minecraft-forge-server/main/resources/server-mods-2023-12-21.zip"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./resources/mods-config:/config:ro